spring.application.name=rewards-program
server.port=8080

# Logging
logging.level.org.springframework=INFO

# H2 Database
spring.datasource.url=jdbc:h2:mem:rewardsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# H2 Console (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL Initialization
spring.sql.init.mode=always

# Configurable reward window
rewards.last.months=3
